# Site Settings

title: Chris's Site
kicker: "Mind // Body // Soul"

# Build settings

markdown: kramdown
permalink: pretty
highlighter: rouge

port: 8080

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested